### ISSUE TITLE
Google Play Music Playlist

### ISSUE THREAD

**Issue by mstrelan** [nickw444/100-warm-tunas#1]
Thanks for this, I created a Google Play Music playlist for this, see [100 Warm Tunas - 2017 (100-1)](https://play.google.com/music/playlist/AMaBXylXyAgIDvg3ZlEkgVxrrnwVjXk6XHMH5GKxubKjH45A-zqf_pbBGFuN2cWtwFZIHguFx_UOVxfIVAQWzsmyo60klfjIIQ%3D%3D). It's missing the two Like a Version songs. Feel free to post a link on your site.

**Comment by nickw444** [comment]
Thanks!
