### ISSUE TITLE
Graph the results over time

### ISSUE THREAD

**Issue by k4n30** [nickw444/100-warm-tunas#2]
Thought it might be useful to see a graph of the results over time for the duration of the voting period. It would be handy to see how songs change position from voting opening until the end of voting.  Using metadata from your commits might be the first step, unless a suitable method of extracting the data would be better.

Keen to hear your thoughts.

**Comment by nickw444** [comment]
Hi @k4n30 thanks for raising. This is some analysis we perform behind closed doors, but are planning to make it more transparent by publishing it on the website within the next few weeks. Stay tuned.
